language: node_js
node_js:
  - '4.3'
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - npm run coveralls
before_deploy:
  - yarn install --production
deploy:
  provider: lambda
  function_name: ecd-watchdog
  description: Manages state information of ECD deployments
  module_name: index
  handler_name: handle
  role: arn:aws:iam::608300940987:role/lambda-ecd-watchdog
  runtime: nodejs4.3
  memory_size: 128
  timeout: 10
  region: eu-west-1
  access_key_id:
    secure: TiXY7t+mdiAP1H63J5yenc3l7iI7Blini+VsF3npjRDAp2QzDic31l8dzIy97rFvme+qjaX8GV0Iyin7/Rbcqh4ZFkvktenE/2hVgQICBkClrGrvdvCVr4bBJ9+U/Fd9RK8/a28wBBVGlEjpUZpr5hLIi32BbDrW2JY0poSIk8Py1jQlpWIBkrbu/ONSVrGMwd4dVMHZUWzniie2Iupijoabb8wCzSS26ntEvQ45lj2lwRCOmP/f6srgZgyA3aBLBxP7a6NxuXLAEvKpsc+r36tQD90o80CSW4aqm7U8Sjkz0zYZZHTdCUm+6F4hhrHdHkHws5d+f+GNCEVZg7KTl1vLXurgtA2tendcXxWdnmT7dwG0yxqUiI748IUKGz2zM+imD1w9ultbql5Fa8ISupncltsUSapIS4ofmrly/q0sAOfE65lI8oM8rR6IGewjeFCK8ctdMLsWnUQWAzsr98q8v9k8KBBC5vb3Jt0linTRrQVzgz+KHJn2DZgHYgwLXn0XolSOyY6iXFMhO144sR+VKa37bx8Exiu/LrVJzKKt0NGBK83+PvHSNe5B48I6q4l/z6Rfjdk4PZIPFSeRikVHo8icBcyPi7xIPp2CpoATqYpEllf1jlw3404ORaIjF0CP4XBbaJ35h9GCkFPYMPN+uN0A3tJ58aYIjpCigzM=
  secret_access_key:
    secure: P75VZe1SAqq2Z2g+hsfhN6H9ut2gyRMwxZbAqEujQn7i1m4aARDtRvgb8x4WZ4ehGqddKeLZ+JVpumPapVAx4OMMuTEAoy14zdLXOBVos2zbpa5O04RQ/4UeXsfl4QGRWuf1vcOvg2i485Dou9LZXzWulX/XanKPILO7AGb41njJIavzU7/XkvMTBzitYXa0spD+j7U8IFMc31RMsRF+hqBVMoolYY3bByvbaA1PeoYcI+n3X1DElnDAeeOShkEre7a/tR9bCQUdjrfpxHmIw9j68cXyuvmWtu3bp8yy72XtV4KVuHZtMOBg22sFSfW+4byoUktBoW+x9ZGOujz9dASDFfX7CRoRN7Cb0+ddC6s98DsDIZEDPOmeWWOj5nu09bACSSJuyjr9prRowbwea+lMmrhFR2+eIjTMD+tIVdRxgvfz+YyG4sfGq3abQ8QeAgcyY9SgSW1uRQoHCQtH5p2BN6rc8foHmx2jKa0HqfQs7DqtDqXzlPLitlMObQlAA8jLQFMY+N77P0Jo+u1f4SKsWHBbXoE6iNJpjCz3c6cZu1CXPjI7vcTMhisJOXp56UTsxpsSesXt688o98mllLzcddBcR5ciCWvCfZqEjO/aPUtdXHryOHqParbm8tCheOA8ix7tE8DX8NwiS1CV9sOrXRciiquunyBLLJ50JTQ=
  on:
    branch: master
