language: node_js
node_js:
  - '4.3'
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - npm run coveralls
before_deploy:
  - yarn install --production
deploy:
  provider: lambda
  function_name: ecd-watchdog
  description: Manages state information of ECD deployments
  module_name: index
  handler_name: handle
  role: arn:aws:iam::608300940987:role/lambda-ecd-watchdog
  runtime: nodejs4.3
  memory_size: 128
  timeout: 10
  region: eu-west-1
  access_key_id:
    secure: hreoriaWPAF02wujzB3wkoMbhRZ8P22rnMRrgJRHVV5sI9ZFnj//UC1tYoKJmQslYP9xf7veLr77Z8q40EkP8P6HmRt6IzN2HMjAth6H2zIadgxWL9DYZ70sixC8Yk/RRV8yP0VD4eRDCIkCFmLQiwbqiJGrTkI2RBVJJ3h7vvsTIiweHUNgaoNT6R8hM8iBIJpzM+tJp3GlKvzdh2geuj5BmJ1iJhOz7lFh3HUJq6fJRBWHFm9E8aeC9syfkrgZFFUtSgZbpKAmHmJGQSTL7f85aarmrPAKiYHqwpWguNbyIEI+9gOxYStiuK9TrHZjKqtFbXtwYxxiJzQ7ZG+XoDPNZHmmGAfQDP8wduHGPzfzjbUS7et3yVX7jiF+pCMk2YGfsi2Lk8be8dBsRPMtkvWRqiqufRdvgJcyuuTDQvQpaK17dlyz7puFaghIZHRNUqMaaur2AUzWu2EzvxJOQZ8BDYTDAYXxITU+FVp49XiLjfNGKr4+y8HW6m9aNNGrBgkfXAAD21e5Dkqz0ni3nUeOSJoP4L+QHu44lgylUUsnOC1NyjiQ8kpGtnvpTwLfLncwsflLLcLGUDsIm/iNejTSd1i7y4KzJaWRaft0adPA1bT6VtQpoFOejyaTDolpXunY0syIQvgIoY2Tb/uIaZLUS2nsF8DY1qn/yCjrZ4o=
  secret_access_key:
    secure: tqCCKs97UbK4+4icTsFAG+l0kkl2EZe++oC/y6lP/BptFzpweUvcxansCDRJX+y2cI2x4GSWXzNkiVLj0dK7OdoBd8wUCLw8iF0jkJ8riJ31mzEQlfzKY0Xb85S7ZPOA3fYFL3DlJe3g5YXHFCYmWpTH1YHM5gRbw0y2FdtQke8Lk44Rn3yBNOO6SJh9RO3048GmcROFH32xrwTrjS+36Ov78YH7LblssHNoeQWLkQvR6C3hUMmfxkx5BhvL5L59D0eg8KZis8BPwMjAiE8Xc7Fj6c9/oZnfjFnnIpmkU2mDZCAvVq2GPVKSoMQ/Nr37pJQGTnsViybFKyB9udWxh/ebxSukMtQhpA9yVEJgzGR0SYLoRENBa3BNmYGBNNxtms1ULAXhCPdU0qCnmXAtJDTTuYk06EgZoTqE/ICvDYKYkYLox/DpFpxzItyMDqIERjxtLmSjJZcDsDYACH3stBpi5qayvbUQ5opsUSWmKPxv7oLJ9mrA760h4HeqAI+vqqjIq7mXSsaI4/9LXa9tyAfY4GmjmGRhyJRap2lMdrwlLmV44fFzUubidBS29zvGpUcfZQajxrVEO7V/45zu6d+tic5v6ngn1yPDX5Lt08DznjRF+q91OJS2ShwpOL0UiIm/fmGOUxYpST1Abl5dJhJ+MyO/Ct83UsMT40jS7w0=
  on:
    branch: master
