language: node_js
node_js:
  - '4.3'
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - npm run coveralls
before_deploy:
  - yarn install --production
deploy:
  provider: lambda
  function_name: ecd-watchdog
  description: Manages state information of ECD deployments
  module_name: index
  handler_name: handle
  role: arn:aws:iam::608300940987:role/lambda-ecd-watchdog
  runtime: nodejs4.3
  memory_size: 128
  timeout: 10
  region: eu-west-1
  access_key_id:
    secure: cLhfYx3xoON/tZQpbXyuzVl60kUVWuCAb+KipZPppcaH41nRc0wkNTa/ERWBs/AX04ZZfeSkhYv4o9A1Mx05zrzRxo4Pj66dQfsAbXk00Idora0cNSJdCMSscwEegF7/dn4jo26H5iaT+pLmHrOq9cjbvg6sXGvhkO1LBz0B/UiEaDXZlUPMTCw5plTDFkRogRpKSlUBtvMZw/GX8ZOF8muWKW2OR8J8CwFigjNI8LG3U2tPjHC5q1LLwG7wiTt4mwNhvWMSeCyd8/aTAk8+RB/uPQcoiF7qvFbzYGurhlIUtyZt6MahSDPHyOmpp7fiNCBQM3BE1UKO76QUgc1+OL6kxI5ngmOql9i17NBHR1qLDZD7DbI4p/TzISTnUtEI0s+Wq5wJXccZB9FOEWuWIc/G3hFR0gvQ2Vv98h/1fFNbBp9kwv751Dgmmp3JWne7smO6FVh6bAUeHz3gSfVc0M1kMj8NR5ty5hBCEsQ/eCNsmbE3y4CSVqt98x3wIPUcVRYUR6Am1asz67WUvnfZT6MKg8j39xasBr8zbUIT1mPtnRScH+wF4QI1HNvGZ5p4Ev7wmbLF3ynadgrkTR2skaYVtugNTYXskJGFWvBdjAXeniI2fnJmM16GMLO2SNZq6Ah/NE2rJj0kz6SJplW71td4Od3MjL2PEhpx9JYmXVE=
  secret_access_key:
    secure: g2EMJPGMtAGYNT3hY92iHXs+copQAa0ykeuQcyFFZruSYtxm+mTtba18uIxmpsJtzip6UK9X/Wwzzg8J+R+O01XPKXAPIGVQ273XKegaED3RQlGM7z4QhChvNdWTxVMpI23NLGZOY3in9rFjsY9Nj7hsdEfdOFUG54Hxk3egkXfco5rBTw7OtzdsyNKw5gi0/M0rn2VF3ATW5HQMxwoL0v+8q8dJRnbagRlwDAlwe9SKx+3+BdSNDrcDZMruj35uON7ZFoDLlQgoubgyQg15g0jmSAhG/T1pI/ZWyhXLC9BWJHfXsOyrdcU78BBv8g9PcOtrXeCV2qVdaMD8aLxek3IeEWPUM3Han287E7PFV/YcfehurOcb/imoWCApWLksnRaHEHOAxrSd3pgW6OPeNRmHjcGWGabtBGjCLN8rNJY46PGg8eIxgiH+SGtuY10399GckPTNMVB9Adm/6adIviwWlo24Ji1vvSj3qJ3ogw8cu/MQpH87yj6TSA52phJBIhX6KxpkOtk9DOuLbVjHnF9S8VYPk32hLHDLhwg8vcCasBRQlYoJ+JYh67cLAzPC+6CIOAo8rCYj8t49Rj43rDuv7fGpPXTjv6u9REvoxkMXeFOGtYc0jSjLs+k1OfnOAkZV2VdT93lE7fHw0z8uYOoufEYClPcPV5YKEvxOasA=
  on:
    branch: master
